model:
  name: grl
  track_length: 10
  hidden_channels: [24, 32, 32, 48, 48, 64, 64, 96, 160]
  pool_after_layers: [0, 2, 4, 6, 7]
  global_pool: 2
  forget_bias_init: 1.5

data:
  train_root: /home/faenna/grl/image-net1000/layout/train
  eval_root: /home/faenna/grl/image-net1000/layout/val
  image_size: 224
  center_crop: true
  per_gpu_batch_size: 28
  workers: 16
  persistent_workers: true
  prefetch_factor: 2
  pin_memory: true
  drop_last_train: true

train:
  epochs: 50
  grad_accum_steps: 1
  train_gold_prob: 0.5
  aux_h_loss_weight: 0.3
  gradient_clip_norm: 20.0
  use_amp: true
  benchmark: true
  eval_on_main_rank_only: false

optimizer:
  lr: 0.001
  weight_decay: 0.01
  bias_weight_decay: 0.0

scheduler:
  factor: 0.7
  patience: 4
  start_epoch: 6
  window_size: 5
  min_lr: 0.00005
  mode: min

logging:
  progress_every_batches: 50
  progress_every_samples: 0
  jsonl_filename: progress.jsonl
  log_json: true

checkpointing:
  output_dir: /home/faenna/grl/runs/grlnet_a100_single_50e_auxh
  checkpoint_prefix: grl_a100_single_50e_auxh
  save_every_epoch: true
  save_best: true
  resume_from: auto

runtime:
  seed: 42
  device: cuda:0
  ddp_backend: nccl
  tf32: true
